services:
  orgvitality-ai:
    build: .
    container_name: orgvitality-ai-app
    ports:
      - "8000:8000"
    volumes:
      # This path is updated to match the new WORKDIR in the Dockerfile.
      # It mounts your local data folder to /app/data inside the container.
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
